# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IQKeyboardManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IQKeyboardManagerDemo

  target 'IQKeyboardManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IQKeyboardManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'IQKeyboardManager', '~> 6.1.1'

end
